version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore_rest
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  dev-app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: bookstore_rest 
    volumes:
      - .:/app

networks:
  mynetwork:

volumes:
  mysql-data:
